behaviors:
    CarAI:
        trainer_type: ppo
        hyperparameters:
            batch_size: 512
            buffer_size: 10240
            learning_rate: 3.0e-4
            beta: 0.0001
            epsilon: 0.2
            lambd: 0.99
            num_epoch: 3
            learning_rate_schedule: linear
            beta_schedule: constant
            epsilon_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 256
            num_layers: 2
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            gail:
                strength: 0.5
                demo_path: Demos\CarDemo_12.demo
        behavioral_cloning:
            strength: 0.5
            demo_path: Demos\CarDemo_12.demo
        max_steps: 5.0e8
        time_horizon: 256
        summary_freq: 20000
